language: python

python:
 - 2.7
 - 3.5
 - 3.6
 - 3.7

env:
  - NUMPY_VERSION=1.11.0
  - NUMPY_VERSION=1.12.1
  - NUMPY_VERSION=1.14.6
  - NUMPY_VERSION=1.15.4
  - NUMPY_VERSION=1.16.5

matrix:
  exclude:
    - python: 3.6
      env: NUMPY_VERSION=1.11.0

script:
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python -m pip install -U pip
  - pip install -U wheel
  - pip install numpy==$NUMPY_VERSION
  - pip install pytest
  - python setup.py build
  - python -m pytest

